### ISSUE TITLE
Is there a plan to integrate goquic？

### ISSUE THREAD

**Issue by liudanking** [libp2p/go-stream-muxer#7]
QUIC is awsome, especially in low latency situation.
Is there a plan to integrate QUIC using [goquic](https://github.com/devsisters/goquic) ?

**Comment by whyrusleeping** [comment]
QUIC will require a bit more though on how this all will work. QUIC connections have stream creation capabilities on them, where this library takes in an existing connection and does stream multiplexing over the top of it.

We will have to find an abstraction that works for stream muxers at the connection level (and not as a layer above)

**Comment by jbenet** [comment]
- there may be a reason to use quic even over an already reliable channel.
  It's a bit brain damaged, but so is stream muxing over tcp anyway.
- agree with wanting a go-streammuxer that works over an unreliable
  connection
- thanks for pointer to goquid!

**Comment by raulk** [comment]
A few months ago, we introduced the concept of "connection upgraders". Transports now specify how they turn a raw network connection into a fully-fledged libp2p connection (with encryption and multiplexing). Since this is transport-mandated, the [libp2p quic transport](https://github.com/libp2p/go-libp2p-quic-transport) is able to leverage native multiplexing.
